ACTORS = ["CUSTOMER", "SALES", "STOCKS", "FINANCE", # image010
        "FULFILLMENT", "MANAGEMENT", "CREDIT DEPARTMENT", "CUSTOMER SERVICE REPRESENTATIVE", # image020
        "HUMAN RESOURCE", "PAYROLL", "EMPLOYEE", "MANAGER", "PAYROLL VENDOR", # image030
        "CONSULTANT", "DATA ENTRY CLERK", # image040
        "END USER", "BUSINESS ANALYST", # image050
        "PARTNER", "FTP SERVER", # image060
        # image070 header is not captured
        "INCIDENT MANAGER", "SERVICE DESK", # image080 
        "CSR", "PLANT MANAGER","PRE-PRESS OPERATOR", # image090
        "SOFTWARE DEVELOPMENT", "SOFTWARE CODING", "SOFTWARE DESIGN" # image100
        ]